### ISSUE TITLE
Can this be combined with geo_query?

### ISSUE THREAD

**Issue by con322** [bootsz/wp-advanced-search#115]
Do you know if this can be combined/compatible with geo query? Should I just do the search query using your setup as normal and then add within my argument add the following:

     'geo_query' => array(
        'lat'                =>  40.7034747,                                // Latitude point
        'lng'                =>  -73.9795316,                               // Longitude point
        'lat_meta_key'       =>  '_latitude',                          // Meta-key for the latitude data
        'lng_meta_key'       =>  '_longitude',                          // Meta-key for the longitude data 
        'radius'             =>  1,                               // Find locations within a given radius (km)
        'order'              =>  'DESC',                            // Order by distance
        'distance_unit'      =>  111.045,                           // Default distance unit (km per degree)
        'context'            => '\\Birgir\\Geo\\GeoQueryHaversine', // Default implementation, you can use your own here instead.
    ),

**Comment by bootsz** [comment]
I haven't heard of this before, looks interesting though.  My guess would be that it's not compatible but please share your results here if you manage to get it to work.
