### ISSUE TITLE
Multi-column search forms?

### ISSUE THREAD

**Issue by booruguru** [bootsz/wp-advanced-search#117]
I'd like to control the layout of my search forms. I'm especially interested in creating a multi-column search form using a CSS framework like Foundation or Bootstrap. Is there any way wp-advanced-search
could accommodate my needs? If not, how difficult would it be to modify wp-advanced-search to support multi-column forms?

**Comment by bootsz** [comment]
There are many options already built in for customizing the appearance of your forms.  It should give you enough flexibility to tailor the HTML markup & css classes to make it compatible with whatever you want to do.  See:

1. The 'html' field type: http://wpadvancedsearch.com/field/html/
2. The newly-added 'pre_html' and 'post_html' field options https://github.com/growthspark/wp-advanced-search/releases/tag/1.3
3. Enable WPAS_DISABLE_WRAPPERS https://github.com/growthspark/wp-advanced-search/releases/tag/1.3

**Comment by booruguru** [comment]
Thanks.
