### ISSUE TITLE
Can I have the search form show results on a specific page?

### ISSUE THREAD

**Issue by booruguru** [bootsz/wp-advanced-search#118]
I'd like to have a search form available on every page of my site (as a hidden modal window) that returns results on a specific page.

**Comment by bootsz** [comment]
Yes.  You need to change the 'action' attribute of the form to go to a different page:
http://wpadvancedsearch.com/docs/configuration/

See: https://github.com/bootsz/wp-advanced-search/issues/8#issuecomment-24071651

Please search through the resolved issues before opening new tickets.  Chances are that if you have a question someone else has asked about it too :)
