### ISSUE TITLE
Can wp-advanced-search search a range of values (publish dash, custom fields, etc.)?

### ISSUE THREAD

**Issue by booruguru** [bootsz/wp-advanced-search#119]

**Comment by bootsz** [comment]
The next version will support this.  It is available as a beta release (not thoroughly tested) if you'd like to try it out.  Code is here: https://github.com/bootsz/wp-advanced-search/tree/1.4-beta

Currently it works with meta_key fields only, but I plan to add support for dates as well. 

You can search a range in two ways:

1. With a single form input: http://wpadvancedsearch.com/beta/param/compare/

2. With two separate form inputs: http://wpadvancedsearch.com/beta/param/inputs/

If you have success with either of these methods do let me know!
