### ISSUE TITLE
Default value for taxonomy

### ISSUE THREAD

**Issue by DONSA** [bootsz/wp-advanced-search#121]
Hi,
I'm trying to create a select box that allow the user to search all post's with a custom taxonomy.
I want to add a default option like "Select your district" that does't affect the search.
I'm using the 1.4 beta version so I don't know if it's a version problem or I'm doing something wrong...

`$args['fields'][] = array(
                        'type' => 'taxonomy',
                        'taxonomy' => 'distrito',
                        'format' => 'select',
                        'default' => 'Select yout district',
                        'label' => 'Distrito');`

**Comment by bootsz** [comment]
You want 'allow_null', not 'default':

```
'allow_null' => ''Select yout district'
```

**Comment by DONSA** [comment]
That's right. Thanks!

**Comment by chetanpatel786** [comment]
hie DONSA,
Can u please provide me documents on  texonomy..I have never created texonomy in sharePoint 2013.
I will be very thankful to you
