### ISSUE TITLE
Search bettween 0 and x value

### ISSUE THREAD

**Issue by DONSA** [bootsz/wp-advanced-search#125]
Hi,
I have a problem searching between a range of values. Everything works fine except when I search between a range of 0 and other value.
I'm using the beta release.

**Comment by bootsz** [comment]
What happens when you do that?  It seems to work for me.  Try enabling WPAS_DEBUG and post the output here.

**Comment by DONSA** [comment]
The default range is between 0 and 100000.
If I search with that value, returns all articles. If I change the range to 1 and 100000, the search is correct.

`WPAS DEBUG

|| Errors

No errors detected.`

**Comment by bootsz** [comment]
Also please post your field arguments too

**Comment by DONSA** [comment]
`$args['fields'][] = array(
                        'type' => 'meta_key',
                        'meta_key' => 'wpcf-preco',
                        'compare' => 'BETWEEN',
                        'data_type' => 'NUMERIC',
                        'inputs' => array(
                                        array(
                                            'format' => 'number',
                                        ),
                                        array(
                                            'format' => 'number',
                                        )
                                    )
                        );`

**Comment by DONSA** [comment]
`$args['fields'][] = array(
                        'type' => 'meta_key',
                        'meta_key' => 'wpcf-preco',
                        'compare' => 'BETWEEN',
                        'data_type' => 'NUMERIC',
                        'inputs' => array(
                                        array(
                                            'format' => 'number',
                                        ),
                                        array(
                                            'format' => 'number',
                                        )
                                    )
                        );`

**Comment by bootsz** [comment]
Ok.  Also the debug output should also include the WP_Query object and MySQL information.  Can you post that as well?

**Comment by DONSA** [comment]
`WPAS DEBUG

|| Errors

No errors detected.

|| WP_Query Arguments

Array
(
    [post_type] => Array
        (
            [0] => imoveis
        )

    [oderby] => title
    [order] => ASC
    [type] => posts_per_page
    [paged] => 1
)


|| MySQL Query 

SELECT SQL_CALC_FOUND_ROWS  wp_cdpiposts.ID FROM wp_cdpiposts   JOIN wp_cdpiicl_translations t ON wp_cdpiposts.ID = t.element_id
						AND t.element_type IN ('post_imoveis') JOIN wp_cdpiicl_languages l ON t.language_code=l.code AND l.active=1 WHERE 1=1  AND wp_cdpiposts.post_type = 'imoveis' AND (wp_cdpiposts.post_status = 'publish' OR wp_cdpiposts.post_status = 'private') AND t.language_code='pt-pt'  ORDER BY wp_cdpiposts.post_date ASC LIMIT 0, 10`

**Comment by DONSA** [comment]
After click search:

`WPAS DEBUG

|| Errors

No errors detected.

|| WP_Query Arguments

Array
(
    [post_type] => Array
        (
            [0] => imoveis
        )

    [oderby] => title
    [order] => ASC
    [type] => posts_per_page
    [meta_query] => Array
        (
            [0] => Array
                (
                    [key] => wpcf-preco
                    [type] => NUMERIC
                    [value] => Array
                        (
                            [0] => 1000000
                        )

                    [compare] => BETWEEN
                )

        )

    [paged] => 1
)


|| MySQL Query 

SELECT SQL_CALC_FOUND_ROWS  wp_cdpiposts.ID FROM wp_cdpiposts  INNER JOIN wp_cdpipostmeta ON ( wp_cdpiposts.ID = wp_cdpipostmeta.post_id )  JOIN wp_cdpiicl_translations t ON wp_cdpiposts.ID = t.element_id
						AND t.element_type IN ('post_imoveis') JOIN wp_cdpiicl_languages l ON t.language_code=l.code AND l.active=1 WHERE 1=1  AND ( 
  wp_cdpipostmeta.meta_key = 'wpcf-preco'
) AND wp_cdpiposts.post_type = 'imoveis' AND (wp_cdpiposts.post_status = 'publish' OR wp_cdpiposts.post_status = 'private') AND t.language_code='pt-pt' GROUP BY wp_cdpiposts.ID ORDER BY wp_cdpiposts.post_date ASC LIMIT 0, 10`

**Comment by bootsz** [comment]
I think I've fixed it.  Re-download the code and give it a try

**Comment by DONSA** [comment]
Worked, thanks!
