### ISSUE TITLE
Search more than one custom taxonomy

### ISSUE THREAD

**Issue by DONSA** [bootsz/wp-advanced-search#126]
Hi,
I want allow the user to search posts that have specific custom taxonomy. I'm using checkboxes for that.
The problem is that the WP Advance Search only returns posts that have all the taxonomies selected.
I want them to search for posts that have at least one of the selected taxonomies.
I hope you understand.

**Comment by bootsz** [comment]
If you're using the beta release, you need:

```
$args['config']['taxonomy_relation'] = 'AND';
```

http://wpadvancedsearch.com/beta/docs/configuration/

**Comment by DONSA** [comment]
Thanks
