### ISSUE TITLE
Relevanssi Premium issues

### ISSUE THREAD

**Issue by kimlawler** [bootsz/wp-advanced-search#127]
Hey guys, 

Wasn't sure the best place to put this. Seen a few people mentioning issues with Relevanssi... 

I've been setting up the wp-advanced-search with Relevanssi Premium (1.13.4) just now, and was suffering from no results with search terms. A little debugging later and the problem's down to line 872 in wpas.php, where the Relevanssi plugin's called. The premium plugin has a different directory name (relevanssi-premium), quick change to wpas.php has fixed the issue:

```
if ($this->relevanssi) {
                include_once( ABSPATH . 'wp-admin/includes/plugin.php' );
                if (!empty($_REQUEST['search_query']) && is_plugin_active('relevanssi-premium/relevanssi.php')) {
                    relevanssi_do_query($query);
                }
            }
```

**Comment by bootsz** [comment]
Thanks for brining attention to this.  I have applied an update to both the current version (1.3) as well as the beta release to address this.
