### ISSUE TITLE
No search button

### ISSUE THREAD

**Issue by DONSA** [bootsz/wp-advanced-search#128]
Hi,
I've been reading the documentation and I could't find a method that allow the user to search without a search button.
I have only a select box that shows a custom taxonomy. I want to search automatically for a custom taxonomy when the user changes the select box, without having to click the search button.

Is that possible with WP Advance Search?

**Comment by bootsz** [comment]
Yes it can be done but you need to use JavaScript for that.  Currently there is no JavaScript included in the framework so you need to do it yourself.  It's only a couple lines of JS.  You just set an event listener to wait for when the select box value is changed and then make it submit the form.  If you are unsure how to do this try a Google search for how to submit a form using JavaScript.

**Comment by DONSA** [comment]
Thanks @bootsz, it was really simple.

```javascript
$('#tax_paises').change(function(){
        $(this).closest('form').trigger('submit');
});
```

Now, because I have the form in a specific tab, when I submit the form the first tab is loaded.
My first thought was to add the id of the tab in the url or, more complicated, user ajax to submit the form.
How hard would be to implement a solution like this?

**Comment by bootsz** [comment]
I'm not sure since I don't know the specifics of your site but it should be doable by using the tab ID and JavaScript.  Ajax is harder, but if I have time I will be including support for it in the next release.

**Comment by DONSA** [comment]
Thanks.
