### ISSUE TITLE
Search by meta_key not working

### ISSUE THREAD

**Issue by pankaj2892** [bootsz/wp-advanced-search#129]
I want ot filter search using meta_key values. But it is not working.
Below is my code:

define('WPAS_DEBUG', false);
get_header(); 
?>

	<div class="page-body">
		<h1><?php the_title(); ?></h1>

		<?php 
		
			$args = array();

			$args['wp_query'] = array('type' => 'post_type',
											'post_type' => 'restaurant',
			                                'posts_per_page' => 5,
			                                'order' => 'DESC',
			                                'orderby' => 'date');

			$args['fields'][] = array('type' => 'search',
			                                'label' => 'Store Name',
			                                'value' => '');

			$args['fields'][] = array('type' => 'taxonomy',
				                                'label' => 'City',
				                                'taxonomy' => 'restaurantcat',
				                                'format' => 'select',
				                                'operator' => 'IN');

			$args['fields'][] = array('type' => 'meta_key',
			                          'key' => 'rest_street',
			                          'label' => 'Search by street',
			                          'compare' => '=',
			                          'values' => array('100 W Ontario St' => '100 W Ontario St', '601 W. Adams' => '601 W. Adams', '710 Schneider Dr' =>'710 Schneider Dr')
			                    );

			$args['fields'][] = array('type' => 'submit',
			                                'value' => 'Search');

			$my_search_object = new WP_Advanced_Search($args);

**Comment by bootsz** [comment]
Try setting 'compare' => 'LIKE'

Also turn out WPAS_DEBUG and post the output here

**Comment by pankaj2892** [comment]
Used 'compare' => 'LIKE'
But no luck.
Output after turning on WPAS_DEBUG

WP_Query Object
(
    [query] => Array
        (
            [type] => post_type
            [post_type] => restaurant
            [posts_per_page] => 5
            [order] => DESC
            [orderby] => date
            [tax_query] => Array
                (
                    [0] => Array
                        (
                            [taxonomy] => restaurantcat
                            [field] => slug
                            [terms] => chicago
                            [operator] => IN
                        )

                )

            [paged] => 1
        )

    [query_vars] => Array
        (
            [type] => post_type
            [post_type] => restaurant
            [posts_per_page] => 5
            [order] => DESC
            [orderby] => date
            [tax_query] => Array
                (
                    [0] => Array
                        (
                            [taxonomy] => restaurantcat
                            [field] => slug
                            [terms] => chicago
                            [operator] => IN
                        )

                )

            [paged] => 1
            [error] => 
            [m] => 
            [p] => 0
            [post_parent] => 
            [subpost] => 
            [subpost_id] => 
            [attachment] => 
            [attachment_id] => 0
            [name] => 
            [static] => 
            [pagename] => 
            [page_id] => 0
            [second] => 
            [minute] => 
            [hour] => 
            [day] => 0
            [monthnum] => 0
            [year] => 0
            [w] => 0
            [category_name] => 
            [tag] => 
            [cat] => 
            [tag_id] => 
            [author] => 
            [author_name] => 
            [feed] => 
            [tb] => 
            [comments_popup] => 
            [meta_key] => 
            [meta_value] => 
            [preview] => 
            [s] => 
            [sentence] => 
            [fields] => 
            [menu_order] => 
            [category__in] => Array
                (
                )

            [category__not_in] => Array
                (
                )

            [category__and] => Array
                (
                )

            [post__in] => Array
                (
                )

            [post__not_in] => Array
                (
                )

            [tag__in] => Array
                (
                )

            [tag__not_in] => Array
                (
                )

            [tag__and] => Array
                (
                )

            [tag_slug__in] => Array
                (
                )

            [tag_slug__and] => Array
                (
                )

            [post_parent__in] => Array
                (
                )

            [post_parent__not_in] => Array
                (
                )

            [author__in] => Array
                (
                )

            [author__not_in] => Array
                (
                )

            [ignore_sticky_posts] => 
            [suppress_filters] => 
            [cache_results] => 1
            [update_post_term_cache] => 1
            [update_post_meta_cache] => 1
            [nopaging] => 
            [comments_per_page] => 50
            [no_found_rows] => 
            [taxonomy] => restaurantcat
            [term] => chicago
        )

    [tax_query] => WP_Tax_Query Object
        (
            [queries] => Array
                (
                    [0] => Array
                        (
                            [taxonomy] => restaurantcat
                            [terms] => Array
                                (
                                    [0] => chicago
                                )

                            [field] => slug
                            [operator] => IN
                            [include_children] => 1
                        )

                )

            [relation] => AND
            [table_aliases:protected] => Array
                (
                    [0] => wp_term_relationships
                )

            [queried_terms] => Array
                (
                    [restaurantcat] => Array
                        (
                            [terms] => Array
                                (
                                    [0] => chicago
                                )

                            [field] => slug
                        )

                )

            [primary_table] => wp_posts
            [primary_id_column] => ID
        )

    [meta_query] => WP_Meta_Query Object
        (
            [queries] => Array
                (
                )

            [relation] => 
            [meta_table] => 
            [meta_id_column] => 
            [primary_table] => 
            [primary_id_column] => 
            [table_aliases:protected] => Array
                (
                )

        )

    [date_query] => 
    [request] => SELECT SQL_CALC_FOUND_ROWS  wp_posts.ID FROM wp_posts  INNER JOIN wp_term_relationships ON (wp_posts.ID = wp_term_relationships.object_id) WHERE 1=1  AND ( 
  wp_term_relationships.term_taxonomy_id IN (100,103,104,105,106)
) AND wp_posts.post_type = 'restaurant' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'closed' OR wp_posts.post_status = 'private' OR wp_posts.post_status = 'hidden') GROUP BY wp_posts.ID ORDER BY wp_posts.post_date DESC LIMIT 0, 5
    [posts] => Array
        (
            [0] => WP_Post Object
                (
                    [ID] => 5834
                    [post_author] => 1
                    [post_date] => 2015-04-25 09:56:26
                    [post_date_gmt] => 2015-04-25 09:56:26
                    [post_content] => Probably the best place to get a hotdog in RL. Get it with everything which includes mustard,pickle,tomato,relish,sport pepper, sour kraut, and celery salt. Its delicious. Plus the fries are freshly hand cut.Italian Beef Is Excellent. Cant get any better then that!!! 
                    [post_title] => Scotty's Hot Dog Stand - Round Lake Beach IL.
                    [post_excerpt] => 
                    [post_status] => publish
                    [comment_status] => open
                    [ping_status] => open
                    [post_password] => 
                    [post_name] => scottys-hot-dog-stand-round-lake-beach-il-2
                    [to_ping] => 
                    [pinged] => 
                    [post_modified] => 2015-04-30 08:55:28
                    [post_modified_gmt] => 2015-04-30 08:55:28
                    [post_content_filtered] => 
                    [post_parent] => 0
                    [guid] => http://templatefair.com/italianbeef/?restaurant=scottys-hot-dog-stand-round-lake-beach-il-2
                    [menu_order] => 0
                    [post_type] => restaurant
                    [post_mime_type] => 
                    [comment_count] => 0
                    [filter] => raw
                )

            [1] => WP_Post Object
                (
                    [ID] => 5808
                    [post_author] => 1
                    [post_date] => 2015-04-25 06:06:49
                    [post_date_gmt] => 2015-04-25 06:06:49
                    [post_content] => WE LAY IT ON THICK! ?A Beggars Pizza offers a variety of food options- from appetizers, to salads, sandwiches, burgers, pasta, pizza and dessert. ?A Our specialty is our thin crust pizza. ?A We also offer gourmet deep dish and stuffed crust pizza, sure to fill you up. ?A We stay true to our motto- offering quality ingredients piled on. ?A At this location we offer an express lunch line, table service, a bar, carry-outs, delivery, outside dining and catering. ?A We feature specialty slices of the week, as well as many daily drink specials. ?A Check out our website or come on in for more information. Established in 1976 Family owned for over 35 years. ?A The tradition began when Angelo opened the doors in 1976 with his sons Larry & Peter. ?A Due to the success and popularity of their original location on 127th & Western in Blue Island- Larry and Peter decided that it was time to begin expanding. ?A As the popularity and demand grew for Beggars Pizza over the years they continued expansion and now have 9 family owned locations and 9 franchises. ?A All of the franchise owners continue the tradition of family owned and operated restaurants. ?A Each year the family continues to grow and carry on the quality and reputation of Beggars Pizza.
                    [post_title] => Beggars Pizza - Chicago Loop
                    [post_excerpt] => 
                    [post_status] => publish
                    [comment_status] => open
                    [ping_status] => open
                    [post_password] => 
                    [post_name] => beggars-pizza-chicago-loop-2
                    [to_ping] => 
                    [pinged] => 
                    [post_modified] => 2015-04-25 06:36:57
                    [post_modified_gmt] => 2015-04-25 06:36:57
                    [post_content_filtered] => 
                    [post_parent] => 0
                    [guid] => http://templatefair.com/italianbeef/?restaurant=beggars-pizza-chicago-loop-2
                    [menu_order] => 0
                    [post_type] => restaurant
                    [post_mime_type] => 
                    [comment_count] => 0
                    [filter] => raw
                )

            [2] => WP_Post Object
                (
                    [ID] => 5807
                    [post_author] => 1
                    [post_date] => 2015-04-25 06:04:59
                    [post_date_gmt] => 2015-04-25 06:04:59
                    [post_content] => 14 locations in the Chicagoland area. Serving Pizza,Italian Beef, Sandwiches, salads and other Italian tasty treats. 
                    [post_title] => Bacci Pizzeria - South Loop
                    [post_excerpt] => 
                    [post_status] => publish
                    [comment_status] => open
                    [ping_status] => open
                    [post_password] => 
                    [post_name] => bacci-pizzeria-south-loop-2
                    [to_ping] => 
                    [pinged] => 
                    [post_modified] => 2015-04-25 06:33:32
                    [post_modified_gmt] => 2015-04-25 06:33:32
                    [post_content_filtered] => 
                    [post_parent] => 0
                    [guid] => http://templatefair.com/italianbeef/?restaurant=bacci-pizzeria-south-loop-2
                    [menu_order] => 0
                    [post_type] => restaurant
                    [post_mime_type] => 
                    [comment_count] => 0
                    [filter] => raw
                )

            [3] => WP_Post Object
                (
                    [ID] => 5806
                    [post_author] => 1
                    [post_date] => 2015-04-25 06:03:23
                    [post_date_gmt] => 2015-04-25 06:03:23
                    [post_content] => What sets Aurelio's apart from other Chicago pizza? We're different because we use only quality ingredients, serve a variety of generous sizes, and specialize in customizing orders to suit each individual taste. Since 1959, the Aurelio family has been devoted to offering the finest pizza, pasta and sandwiches at reasonable prices with fast, courteous, dependable service.
                    [post_title] => Aurelio's - West Loop
                    [post_excerpt] => 
                    [post_status] => publish
                    [comment_status] => open
                    [ping_status] => open
                    [post_password] => 
                    [post_name] => aurelios-west-loop-2
                    [to_ping] => 
                    [pinged] => 
                    [post_modified] => 2015-04-25 06:34:57
                    [post_modified_gmt] => 2015-04-25 06:34:57
                    [post_content_filtered] => 
                    [post_parent] => 0
                    [guid] => http://templatefair.com/italianbeef/?restaurant=aurelios-west-loop-2
                    [menu_order] => 0
                    [post_type] => restaurant
                    [post_mime_type] => 
                    [comment_count] => 0
                    [filter] => raw
                )

            [4] => WP_Post Object
                (
                    [ID] => 5805
                    [post_author] => 1
                    [post_date] => 2015-04-25 06:01:58
                    [post_date_gmt] => 2015-04-25 06:01:58
                    [post_content] => 
                    [post_title] => Augustino's Deli -South Wacker
                    [post_excerpt] => 
                    [post_status] => publish
                    [comment_status] => open
                    [ping_status] => open
                    [post_password] => 
                    [post_name] => augustinos-deli-south-wacker-2
                    [to_ping] => 
                    [pinged] => 
                    [post_modified] => 2015-04-25 06:32:22
                    [post_modified_gmt] => 2015-04-25 06:32:22
                    [post_content_filtered] => 
                    [post_parent] => 0
                    [guid] => http://templatefair.com/italianbeef/?restaurant=augustinos-deli-south-wacker-2
                    [menu_order] => 0
                    [post_type] => restaurant
                    [post_mime_type] => 
                    [comment_count] => 0
                    [filter] => raw
                )

        )

    [post_count] => 5
    [current_post] => -1
    [in_the_loop] => 
    [post] => WP_Post Object
        (
            [ID] => 5834
            [post_author] => 1
            [post_date] => 2015-04-25 09:56:26
            [post_date_gmt] => 2015-04-25 09:56:26
            [post_content] => Probably the best place to get a hotdog in RL. Get it with everything which includes mustard,pickle,tomato,relish,sport pepper, sour kraut, and celery salt. Its delicious. Plus the fries are freshly hand cut.Italian Beef Is Excellent. Cant get any better then that!!! 
            [post_title] => Scotty's Hot Dog Stand - Round Lake Beach IL.
            [post_excerpt] => 
            [post_status] => publish
            [comment_status] => open
            [ping_status] => open
            [post_password] => 
            [post_name] => scottys-hot-dog-stand-round-lake-beach-il-2
            [to_ping] => 
            [pinged] => 
            [post_modified] => 2015-04-30 08:55:28
            [post_modified_gmt] => 2015-04-30 08:55:28
            [post_content_filtered] => 
            [post_parent] => 0
            [guid] => http://templatefair.com/italianbeef/?restaurant=scottys-hot-dog-stand-round-lake-beach-il-2
            [menu_order] => 0
            [post_type] => restaurant
            [post_mime_type] => 
            [comment_count] => 0
            [filter] => raw
        )

    [comment_count] => 0
    [current_comment] => -1
    [found_posts] => 209
    [max_num_pages] => 42
    [max_num_comment_pages] => 0
    [is_single] => 
    [is_preview] => 
    [is_page] => 
    [is_archive] => 1
    [is_date] => 
    [is_year] => 
    [is_month] => 
    [is_day] => 
    [is_time] => 
    [is_author] => 
    [is_category] => 
    [is_tag] => 
    [is_tax] => 1
    [is_search] => 
    [is_feed] => 
    [is_comment_feed] => 
    [is_trackback] => 
    [is_home] => 
    [is_404] => 
    [is_comments_popup] => 
    [is_paged] => 
    [is_admin] => 
    [is_attachment] => 
    [is_singular] => 
    [is_robots] => 
    [is_posts_page] => 
    [is_post_type_archive] => 
    [query_vars_hash:WP_Query:private] => 870d6985e778eeb91825cfa7d4cb153f
    [query_vars_changed:WP_Query:private] => 
    [thumbnails_cached] => 
    [stopwords:WP_Query:private] => 
)

**Comment by bootsz** [comment]
Oh, I think it's this:

```
'key' => 'rest_street'
```

Should be:

```
'meta_key' => 'rest_street'
```

**Comment by pankaj2892** [comment]
Thanks buddy, Made changes according to you guidelines, Now working perfectly fine.

Thanks
