### ISSUE TITLE
Search by rangle slide !

### ISSUE THREAD

**Issue by Shehab-Eltawel** [bootsz/wp-advanced-search#131]
Does it support search by range sliders like http://refreshless.com/nouislider/  ?

**Comment by bootsz** [comment]
If you use the beta release (1.4) I think you could get it to work.  You'd need to use two inputs like here I think:

http://wpadvancedsearch.com/beta/param/inputs/

And then use jQuery to target the inputs accordingly.

**Comment by Shehab-Eltawel** [comment]
Thanks. that's working.
