### ISSUE TITLE
How do detect if theres an active search

### ISSUE THREAD

**Issue by lmartins** [bootsz/wp-advanced-search#132]
Is there a way do detect if theres an active search so that I can switch which parts of the template to show accordingly?

Many Thanks.

**Comment by bootsz** [comment]
When a search form is submitted there is a variable called 'wpas' in the request.  You can check it with PHP like:

```
if ($_REQUEST['wpas'] == 1) :
```
To see if it is set.

**Comment by lmartins** [comment]
Thank you!
