### ISSUE TITLE
Generic Fields in 1.4 Beta

### ISSUE THREAD

**Issue by jillmolloy** [bootsz/wp-advanced-search#133]
Firstly, thanks for building this. It's been a huge help.

I'm working with the 1.4 beta at the moment and I've noticed that the generic fields are using their type for their ID instead of their ID. I'm currently using two generic fields in my form so this is causing an issue. I've given both fields an ID, but they're still returning their ID as generic.

Here's how I'm registering the fields:
```
  $search_args['fields'][] = array(
    'type' => 'generic',
    'id' => 'postal',
    'format' => 'text',
    'label' => 'Postal Code'
  );
  $search_args['fields'][] = array(
    'type' => 'generic',
    'id' => 'distance',
    'format' => 'select',
    'label' => 'Distance',
    'values' => array(
      5 => 'Within 5 miles',
      10 => 'Within 10 miles',
      20 => 'Within 20 miles',
      50 => 'Within 50 miles',
      100 => 'Within 100 miles'
    )
  );
```

Here's how they're returning in the inspector:

![image](https://cloud.githubusercontent.com/assets/2910546/8335936/9e2af266-1a55-11e5-9398-501633ac7c49.png)

I can probably figure out a workaround for this in the meantime, but just wanted to let you know in case it was useful for you in development.

Thanks again!

**Comment by bootsz** [comment]
Whoops, yeah that is definitely not right.  I have fixed the bug.  Be warned that I recently pushed some substantial updates to the 1.4-beta branch, so depending on when you obtained the code you may need to make some adjustments in your theme.  I think the only thing that differs is how you configure your form (see this page: http://wpadvancedsearch.com/beta/docs/).  I'm trying to update the rest of the documentation as fast as possible, hopefully within the next week or so.  Thanks for catching this bug.
