### ISSUE TITLE
How to insert two text type with between compare in one div?

### ISSUE THREAD

**Issue by Joci93** [bootsz/wp-advanced-search#135]
This is the default options:
$args['fields'][] = array( 'type' => 'page', 
                           'placeholder' => min',
                          'format' => 'text',
);
Picture :http://prntscr.com/7o8mdv

But, i need to insert two text field with 'BETWEEN' compare parameters. How can i do this?

Picture:http://prntscr.com/7o8li2

EDIT:
Oh, i found it here: http://wpadvancedsearch.com/beta/param/inputs/

**Comment by SolidDev** [comment]
Set 'compare' => 'BETWEEN', in the fields config.
