### ISSUE TITLE
Compare LIKE with values array, is it possible?

### ISSUE THREAD

**Issue by Joci933** [bootsz/wp-advanced-search#138]
I have this code, but it's failed because if compare if 'LIKE' the values need to be string, but i need compare -> like and values->array.

Code:
$args['fields'][] = array(
                  'type' => 'meta_key',
                  'label' => 'test',
                  'meta_key' => 'property_extras',
                  'format' => 'checkbox',
                   'data_type' => 'CHAR',
                  'operator' => 'AND',
                  'compare' => 'LIKE',
                  'values' => array('a:1:{i:0;s:15:"property_balcon";}' => 'Erkély',
                  					'a:1:{i:0;s:9:"Központi";}'=>'Kocsibeálló',
                  					'a:1:{i:0;s:28:"Központi (egyedi mérővel)";}'=>'Garázs',
                  					'a:2:{i:0;s:13:"Házközponti"'=>'Lift',
                  					'a:1:{i:0;s:32:"Házközponti (egyedi mérővel)";}'=>'Pince',
                  					'a:1:{i:0;s:6:"Egyedi";}'=>'Tároló',
                  					'a:1:{i:0;s:7:"Villany";}'=>'Klíma'	
									));		

This is possible?

**Comment by bootsz** [comment]
Yes, in the newest version (1.4) you can do this with `data_type => ARRAY<CHAR>`

See: http://wpadvancedsearch.com/param/data_type/
and http://wpadvancedsearch.com/docs/plugins/

Also, don't use the serialized strings in your 'values' array.  Just use the normal values (eg "property_balcon").

**Comment by Joci933** [comment]
Oh, you are awesome. Thanks :) :+1:
