### ISSUE TITLE
Is it possible to clear the AJAX search results?

### ISSUE THREAD

**Issue by tkmain** [bootsz/wp-advanced-search#140]
Hello,

This is an awesome framework!  I have everything setup and it functions great.  However, once the user searches for a term, the term and the results stay in the search field and results div.  Is there a way to force the form and AJAX results to reset when the page reloads?  I've tried both the clear and reset buttons in the form args and they don't accomplish the task.

Working example here:  https://www.loqalmaps.com/location/crested-butte

Click on the search icon, search for 'cafe' and then refresh the page.  If you click on the search icon again, the results and search term will still be there.

Thanks.

**Comment by bootsz** [comment]
That's a good question.  I guess I overlooked that. When I built out the AJAX feature I was trying to replicate the behavior of the non-ajax search forms which preserve form data and results when the page is refreshed.  I will try to put an update together in the next few days that will add a configuration option to control this.  If you need a quick fix, you can go into js/scripts.js  and change line 116 to

```
var storage = null;
```

I'm pretty sure that will give you the behavior you want.

**Comment by tkmain** [comment]
Worked like a champ.  Thanks for the quick response.  I'll keep an eye out for the update with the config option.  This is definitely the best advanced search option I've ever used for WP.  Thanks!
