### ISSUE TITLE
$args['fields'] no results

### ISSUE THREAD

**Issue by d3s1gnw** [bootsz/wp-advanced-search#142]
Good day Sean,

The strangest thing just happened.

- I uploaded the newly 1.4 on his destination on the server.
- Created a new template for 1.4 
- created the template file for ajax results
- added the wpas.php and add_action in the functions.php (old ones deleted and nowhere in the code to be found!)

Without adding the Field types everything loads, debug shows no errors and the corresponding results are there.
But whenever (no matter what kind of Field, for example search:
```
$args['fields'][] = array( 
	'type' => 'search',
	'format' => 'text',
	'placeholder' => 'Enter search terms' 
);
```

the site only loads everything before the : 
$aanbod_search = new WP_Advanced_Search('aanbod_formulier');
from there on it's empty.
No errors displaying or any kind of that.

Plugins using: ACFpro, contactform,jetpack,wpallimport
but these aren't conflicting with wpas

It's probably something stupid I forgot, but working on it for some time now and can't find it anywhere :/

Here are my files:

functions.php:
```
require_once('wp-advanced-search/wpas.php');
	
add_action("init", function() {
	$form_id = 'aanbod_formulier';
	$args = array();
	
		$args['wp_query'] = array(
			'post_type' => 'woningen',
			'posts_per_page' => 12,
			 'type' => 'projecten'
		);


	$args['debug'] = true;
	$args['debug_level'] = 'verbose';

	$args['form'] = array( 
		'auto_submit' => true
	);
	
	$args['form']['ajax'] = array(  
		'enabled' => true,
		'show_default_results' => true,
		'results_template' => '/ajax-resultaten.php',
		'button_text' => 'Laad meer resultaten'
	);		

// without these fields it works

	$args['fields'][] = array( 
		'type' => 'html',
		'placeholder' => '<div class="medium-8 columns search"><span>'
	);

	$args['fields'][] = array( 
		'type' => 'search',
		'format' => 'text',
		'placeholder' => 'Enter search terms' 
	);

	$args['fields'][] = array( 
		'type' => 'html',
		'placeholder' => '</span></div>' 
	);

// end fields	    
                       
	register_wpas_form($form_id, $args); });
```

Template file
```
<?php get_header();
	$aanbod_search = new WP_Advanced_Search('aanbod_formulier');
?>
<section id="projecten">
	<div class="row">
		<div class="medium-12 columns content">
			<div data-magellan-expedition="fixed">
				<div class="medium-4 columns">
					<h1 class="dotted">
						<span><?php wp_title(''); ?></span>
					</h1>
				</div>
				<?php $aanbod_search->the_form(); ?>					
			</div>
		</div>
		<hr />
	</div>
	<div id="aanbod">
		<div id="wpas-debug"></div>
		<div id="wpas-results" class="row">
		</div>
	</div>
</section>

<?php get_footer(); ?>
```

ajax-resultaten.php
is the same as templates/template-ajax-results.php

///
Update on this issue:
from wordpress debugmode: 
Fatal error: Cannot access self:: when no class scope is active in (dirtotemplate)/wp-advanced-search/src/Enum/BasicEnum.php on line 17

**Comment by bootsz** [comment]
What PHP version are you running?

**Comment by d3s1gnw** [comment]
At the moment PHP 5.3
And the Mysql server is running at 5.1.73

**Comment by bootsz** [comment]
Hmmm that is very strange. The error message doesn't really even make sense to me. What is the PHP minor version number (5.3.x) ?

Also, try replacing the entire contents of BasicEnum.php with this code: http://pastie.org/private/baspz5bnlhwbcqdmpxt8aa

There's a chance that might fix it.

**Comment by d3s1gnw** [comment]
Hey Sean, 
It certainly is strange, but after replacing the contents of BasicEnum.php it works like a charm now :dancers: 

Thanks so much!

PHP version: 5.3.3, handler: Apache module

**Comment by bootsz** [comment]
Ok good to know.  Glad it's working

**Comment by jallescaetano** [comment]
@bootsz and @d3s1gnw 

Good afternoon,
I am with this same problem, using the same version of PHP, I've tried replacing the file in question, plus the problem persists. could help me?

**Comment by shorouk** [comment]
I've got the same issue and the code above solved it for me! Thanks @bootsz :)

**Comment by foxykat** [comment]
@bootsz Can you re-add the link for BasicEnum.php ? I have the same issue, the link you gave is now a 404. 

I am stuck using PHP 5.3.3 and  the webmaster can't upgrade the php version :(
