### ISSUE TITLE
Populate Select Field Based on another Select Field

### ISSUE THREAD

**Issue by creativz** [bootsz/wp-advanced-search#144]
How can I create Search Using 2 Select Field:

Select Field 1:

It contains Parent Categories

Select Field 2:

It should list the Child Categories based on the selected Parent Category

___

Is this possible?

Thanks!

**Comment by bootsz** [comment]
It should be possible using some custom jQuery.  You could create all of the possible child category fields and hide them by default with CSS.  Then show/hide the appropriate fields whenever the parent field changes.  It's a bit complicated but doable.
