### ISSUE TITLE
wpas-scripts is being enqueued from Parent Theme Folder

### ISSUE THREAD

**Issue by bhargavy** [bootsz/wp-advanced-search#145]
In my child theme I have placed this code in the functions.php file

    // Include the WP Advanced Search Framework
    require_once('wp-advanced-search/wpas.php');

However the path of the wpas-scripts script being enqueued is 

    http://127.0.0.1/wp/wp-content/themes/parent-theme/wp-advanced-search/js/scripts.js

**Comment by bootsz** [comment]
In lib.php, line 12 change `get_template_directory_uri()` to `get_stylesheet_directory_uri()`.  I think that will fix it.  Let me know if it does and I will apply a patch to the latest release.

**Comment by bhargavy** [comment]
Yes using `get_stylesheet_directory_uri()` fixed it

**Comment by bootsz** [comment]
Ok thanks.  This will be fixed in the upcoming patch.
