### ISSUE TITLE
AJAX search not firing; standard search works fine

### ISSUE THREAD

**Issue by jfc4** [bootsz/wp-advanced-search#147]
Using WPAS v1.4. 

Standard search works fine; updated my standard WPAS code and templates to support AJAX (in accordance with docs and demos), but it doesn't fire at all. I get no results, the loading image doesn't show, nothing shows up in debug, nothing in the web console. 

Code - https://gist.github.com/jfc4/02b9f2974368ec751146

**Comment by bootsz** [comment]
Check the javascript console in your browser using Chrome dev tools or Firebug.  See if there are any errors there.

**Comment by jfc4** [comment]
@bootsz Thanks for the suggestion; I had used Firefox's js console, and no errors displayed. But when I checked Chrome's console, I was receiving a 404 error for /wp-advanced-search/js/scripts.js. 

I found the get_wpas_uri() function in the plugin file lib.php, and updated the URL to match the location of the plugin, and now the AJAX is firing. But I still don't see any results; the timer just spins without stopping.

Now I'm seeing another error message from the js console: "Uncaught SyntaxError: Unexpected token <", and it refers to line 1 of my site domain. When I clicked on the reference link, it points to where the !DOCTYPE is located, but there's nothing wrong there. I've deactivated plugins, and removed other 3rd party js files, but am still getting the hanging load and error msg. I even checked out /js/scripts.js to see if there were any stray "<"s, but didn't see any.

Any thoughts on why I might be getting this error?

**Comment by jfc4** [comment]
@bootsz Ok, I've managed to get the results, and i the process have found a couple of things worth noting:

1 - In order to see the search results, I had to remove the 'results_template' argument from $args['form']['ajax']. If I include 'results_template' (no matter where it is located), then I get the "Uncaught SyntaxError" message referenced above, and the results don't load (Chrome & FF).

2 - When I open the page where my search form is located, the results display automatically, even though I set the ''show_default_results' to false.

**Comment by bootsz** [comment]
Thanks for looking into it.  The first problem is likely happening because you have no such template 'template-ajax-results.php' in your theme root.  I've added an extra note to the demo to prevent confusion about this.  I will also add a more informative error message for when this occurs.

The second issue is likely a side-effect of the browser localstorage being used to preserve the search state.  It seems this feature (though well-intentioned) is causing confusion for people, so I may have to remove it or find another solution.  For now you can use a quick fix, see here: https://github.com/bootsz/wp-advanced-search/issues/140#issuecomment-120061547

**Comment by jfc4** [comment]
@bootsz - Thanks again for your response. Really great work you have done on this project. Thanks for the heads up on issue #140, will check it out.

Sidenote: I had already copied the template-ajax-results.php into my theme root, and still got the error, when referencing it there by argument. Once I commented out the 'results_template' argument, then by default it referenced the default results template that came with the plugin, so it still worked. But when I tried to specify a template, I kept getting that error. 

I need different templates for different searches, which is why I was trying to specify it. Will report back if I have any more updates.

**Comment by jfc4** [comment]
@bootsz - Okay, I re-confirmed that using the 'results_template' argument throws the "Uncaught SyntaxError: Unexpected token <" error, even with template-ajax-results.php in the theme root. I'm wondering if it has to do with the dataType, but I checked /js/scripts.js and the dataType isn't specified.

Not sure what else to do here.

**Comment by bootsz** [comment]
Where is the wp-advanced-search folder located in your installation?

**Comment by jfc4** [comment]
It is located in a subfolder of the theme (/inc/helpers).

**Comment by bootsz** [comment]
Ok.  Yeah I know what the problem is then.  I have put together a patch which should resolve the template issue.  Try grabbing this code: https://github.com/bootsz/wp-advanced-search/tree/1.4.1

Also, to fix the issue with script loading you can set this in wp-config:

```
define('WPAS_URI', get_template_directory_uri() . '/lib/admin/wp-advanced-search');
```

**Comment by jfc4** [comment]
@bootsz Thanks for your help. I moved the plugin to the theme root and everything works fine. But the patch is definitely preferred.

**Comment by bootsz** [comment]
Great!
