### ISSUE TITLE
Costumize form

### ISSUE THREAD

**Issue by DONSA** [bootsz/wp-advanced-search#149]
Hi,
Its possible to customize the generated form?
I want something like this:

```
<div class="row">
    <div class="small-12 medium-6 large-6 columns">
            [first selectbox]
    </div>
    <div class="small-12 medium-6 large-6 columns">
           [second selectbox]
    </div>
</div>
```

**Comment by jfc4** [comment]
@DONSA Yes, in order to customize your form to add in markup, use the 'html' field. First, disable WPAS wrappers in your wp-config.php file, using this code:

```
define('WPAS_DISABLE_WRAPPERS', true);
```

Then use the 'html' field in your form, like below:

```
$args['fields'][] = array('type' => 'html',
			              'value' => '<div class="row"><div class="large-4 medium-4 small-12 columns">'
			              );
```

**Comment by bootsz** [comment]
You can also use the 'pre_html' and 'post_html' arguments on individual form fields to add custom HTML before and after each field.

**Comment by DONSA** [comment]
Worked like a charm. Thanks!
