### ISSUE TITLE
Custom template-ajax-results page

### ISSUE THREAD

**Issue by DONSA** [bootsz/wp-advanced-search#150]
Hi,
It's possible to have a template-ajax-results.php page for each ajax form I have?
I think that WPAS automatically use this template to all my ajax forms.

**Comment by bootsz** [comment]
http://wpadvancedsearch.com/help/

**Comment by DONSA** [comment]
I get it, just have to set it the form args:
´´´'results_template'  => 'template-ajax-results-opportunities.php''´´´

**Comment by amitrahav** [comment]
got the same problem.

updated to version 1.4.1 -
when changing default template i don't get php error but js error on /wp-advanced-search/js/scripts.js?ver=1:
Uncaught SyntaxError: Unexpected token P : 
jQuery.ajax.success	@	scripts.js?ver=1:163
m.Callbacks.j	@	jquery.js?ver=1.11.2:2
m.Callbacks.k.fireWith	@	jquery.js?ver=1.11.2:2
x	@	jquery.js?ver=1.11.2:4
m.ajaxTransport.send.b	@	jquery.js?ver=1.11.2:4


any help?
