### ISSUE TITLE
Support Custom Post Types and Custom Fields in Keyword Search?

### ISSUE THREAD

**Issue by LMDGROUP** [bootsz/wp-advanced-search#155]
I am attempting to integate this solution into our site.  We are using the latest version of WordPress, WP Advanced Search and Relevansee.

In this site we have a custom post type of segments along with a few custom fields.  Relenvansee is configured to search the CPT and some of the fields.  The WordPress default search capability returns the results as expected when searching a keyword.

However I wanted to expand search functionality with this tool.

I am able to successfully create a search page/form with a few filterable searching options, that all appear to filter the custom post type by taxonomies successfully.

However I am unable to search the segments CTP title and custom fields (indexed by Relevansee) by keyword.  The result is... Sorry, no results matched your search.

![image](https://cloud.githubusercontent.com/assets/6145703/9179657/f3084e10-3f6b-11e5-86c2-430700ee7f93.png)

    <?php
    require_once('wp-advanced-search/wpas.php');

    function my_search_form() {
        $args = array();
        $args['wp_query'] =  array( 'post_type' => array( 'segments'  , 'page' , 'field' , 'param' ),
                               'orderby' => 'title', 
                               'order' => 'ASC' );

    $args['debug'] = true ;

    $args['form'] = array( 'auto_submit' => true );

    $args['form']['ajax'] = array( 'enabled' => true,
                                   'show_default_results' => true,
                                   'results_template' => 'template-ajax-results.php', // This file must exist in your theme root
                                   'button_text' => 'View More Results');

    $args['fields'][] = array('type' => 'search',
                              'label' => 'Search',
                              'placeholder' => 'Enter search terms...');

        $args['fields'][] = array( 'type' => 'post_type', 
                               'format' => 'checkbox', 
                               'label' => 'Search by post type', 
                               'default_all' => true,
                               'values' => array('segments' => 'Segments',
                                                 'page' => 'Pages', 
                                                 'field' => 'Fields', 
                                                 'param' => 'Parameters') );

    $args['fields'][] = array('type' => 'taxonomy',
                              'label' => 'Seasons',
                              'taxonomy' => 'seasons',
                              'format' => 'select',
                              'allow_null' => 'Select a season');

     $args['fields'][] = array('type' => 'taxonomy',
                              'label' => 'Categories',
                              'taxonomy' => 'segment-categories',
                              'format' => 'select',
                              'allow_null' => 'Select a category');

     $args['fields'][] = array('type' => 'taxonomy',
                              'label' => 'County',
                              'taxonomy' => 'segment-county',
                              'format' => 'select',
                              'allow_null' => 'Select a county');

    $args['fields'][] = array( 'type' => 'reset',
                               'class' => 'button',
                               'value' => 'Reset' );

    $args['fields'][] = array( 'type' => 'clear',
                               'class' => 'button',
                               'value' => 'Clear' );
    
       register_wpas_form('my-form', $args);    
       }
       add_action('init', 'my_search_form');

**Comment by bootsz** [comment]
Relevanssi has proven to be pretty unpredictable.  I've had success with it on many sites but on others it will just not work, much in the same way you are experiencing, even when using the exact same form, config settings and version of WPAS.  Unfortunately I have not been able to get to the bottom of it.  I'm sorry I can't be more helpful with this.

**Comment by deweydb** [comment]
@LMDGROUP See: https://github.com/bootsz/wp-advanced-search/issues/173
