### ISSUE TITLE
Get specific terms on custom taxonomy

### ISSUE THREAD

**Issue by DONSA** [bootsz/wp-advanced-search#156]
Hi,
I'm trying to show only two terms of a custom taxonomy in a selectbox without success.
He shows all taxonomy terms.

```
$args['fields'][] = array(
        'type'          => 'taxonomy',
        'taxonomy'      => 'paises',
        'term_format'   => 'slug',
        'terms'         => array('brazil-en', 'portugal-en'),
        'format'        => 'select',
        'allow_null'    => __('Select', 'eurotrials')
);
```

**Comment by bootsz** [comment]
This should be fixed now on the latest update: https://github.com/bootsz/wp-advanced-search/archive/master.zip

**Comment by DONSA** [comment]
Thanks

**Comment by jfc4** [comment]
I downloaded the latest version today, and have tried to specify terms for a taxonomy using term_format and terms (I've tried ID and slug formats), but it still defaults to showing all terms. 

Also, when I used term_args => array( 'hide_empty => true ), none of the empty terms are hidden.

**Comment by DONSA** [comment]
Use the version that @bootsz put above.
