### ISSUE TITLE
can't get inputs to work in form.

### ISSUE THREAD

**Issue by mcgujohn** [bootsz/wp-advanced-search#157]
Hi bootsz,

I'm trying to get the inputs in the form to work eventually for three meta_field fields: a 0 - 100 score field, a 0 - 20 score field and price range. I've used the sample args script from the inputs page:
$args = array(
    'type' => 'meta_key',
    'meta_key' => 'price',
    'compare' => 'BETWEEN',
    'data_type' => 'NUMERIC',
    'inputs' => array(
        array(
            'format' => 'number',
            'value' => '0',
        ),
        array(
            'format' => 'number'
            'value' => '50'
        )
    )
);

(by the by, it's missing a comma in the second array after format => number)

This is the code I'm using to do a range search on Score 0 - 20 custom field:

$args = array(
    'type' => 'meta_key',
    'meta_key' => 'S20',
    'compare' => 'BETWEEN',
    'data_type' => 'NUMERIC',
    'inputs' => array(array('format' => 'number', 'value' => '0',),
		      array('format' => 'number', 'value' => '20')));
When I put this at the bottom of the form, none of the fields including this one, appeared. 
When I put it at the top, this fields doesn't appear. I put on the debug and verbose and there were no errors.

PHP Version 5.4.41 WordPress 4.2.4

Here is the debug result up to wp query object dump:
WPAS DEBUG
------------------------------------
|| Errors
------------------------------------
No errors detected.
------------------------------------
|| WP_Query Arguments
------------------------------------
Array
(
    [meta_query] => Array
        (
            [0] => Array
                (
                    [key] => full_list_varieties
                    [compare] => LIKE
                    [value] => Cabernet Shiraz
                    [type] => CHAR
                )

        )

    [paged] => 1
)

------------------------------------
|| MySQL Query 
------------------------------------
SELECT SQL_CALC_FOUND_ROWS  wp_posts.ID FROM wp_posts  INNER JOIN wp_postmeta ON ( wp_posts.ID = wp_postmeta.post_id ) WHERE 1=1  AND ( 
  ( wp_postmeta.meta_key = 'full_list_varieties' AND CAST(wp_postmeta.meta_value AS CHAR) LIKE '%Cabernet Shiraz%' )
) AND wp_posts.post_type = 'post' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'private') GROUP BY wp_posts.ID ORDER BY wp_posts.post_date DESC LIMIT 0, 50
------------------------------------
|| Request Data 
------------------------------------
Array
(
    [search_query] => 
    [meta_vintage] => 
    [meta_full_list_regions] => 
    [meta_full_list_varieties] => Cabernet Shiraz
    [meta_producer_name] => 
    [meta_S100] => 
    [meta_ytd] => 
    [wpas_id] => wine-form
    [wpas_submit] => 1
)

The S20 custom field is not called. Nothing for this field appears on the form.
I've left the S100 select in the form. It works perfectly for selecting one score eg: 74 returns all of the docs with that score.

I've uploaded the full search form function to pastebin here: http://pastebin.com/WmUQu58U
Here's the search results template: http://pastebin.com/unsQ07t5

Not sure what I'm doing wrong. Appreciate being pointed in the right direction to get this working.

Thanks!
John

**Comment by bootsz** [comment]
Your problem is that you are assigning your field arguments directly to the variable $args, rather than to $args['fields'][], which is wiping out the rest of your form.

Change to:

```
$args['fields'][] = array(
'type' => 'meta_key',
'meta_key' => 'S20',
'compare' => 'BETWEEN',
'data_type' => 'NUMERIC',
'inputs' => array(array('format' => 'number', 'value' => '0',),
array('format' => 'number', 'value' => '20')));
```
