### ISSUE TITLE
Error Wpsa  Parse error: syntax error, unexpected T_STRING

### ISSUE THREAD

**Issue by jallescaetano** [bootsz/wp-advanced-search#159]
Good evening, I'm ultizando the WPAS, however up to the project to the web server this error occurs, I searched but found nothing talking about the problem, someone could help me?

Parse error: syntax error, unexpected T_STRING in /home/storage/4/f7/1c/destinodafelicidade/public_html/aq/wp-content/themes/aguasquentes/wp-advanced-search/wpas.php on line 35

**Comment by bootsz** [comment]
What version of PHP are you running?

**Comment by jallescaetano** [comment]
@bootsz  
thank you very much for your help, really the problem was the version of PHP.
