### ISSUE TITLE
2 seperate select inputs based on parent and children Taxonomy

### ISSUE THREAD

**Issue by yefrat** [bootsz/wp-advanced-search#165]
Hi,
i need this to search by area and city under 'Location' taxonomy
when 'area' is the parent and 'city' is her children
after i choose a city i need the form populate all the children options in select dropdown based on the parent term.

Example: 
'North' -> 'City name'

Is it possible to generate this?

Tnx

**Comment by yefrat** [comment]
i have managed to go this far

$args['fields'][] = array(
    'type' => 'taxonomy',
    'taxonomy' => 'location',
    'relation' => 'AND',
    'inputs' => array(
        array(
            'format' => 'select',
            'operator' => 'AND',
            "allow_null" => 'Choose Area',
            'term_args' => array('hide_empty' => true, 'parent' => 0)
        ),
        array(
            'format' => 'select',
            'operator' => 'IN',
            "allow_null" => 'Choose City',
            'term_args' => array('hide_empty' => true, 'orderby' => 'name', 'child_of' => 9)
        )
    )
 
);

all works well now, but i need the city will be based dynamicly on the area, now i manged to do it static....

any help will be great

**Comment by bootsz** [comment]
There is no built-in way to do it dynamically.  You need to use JavaScript for that.  You could include all possible secondary select fields and hide them by default, and show/hide them as necessary when the primary field changes.  You just need to write some jQuery to do it.

**Comment by yefrat** [comment]
tnx,
 i did it with an ajax call based on the parent name.
my final code:
--Javascript
	 <script type="text/javascript">
jQuery(document).ready(function($){
	function ajaxloop() {
    // do your stuff
        var selectedArea = $("#tax_location_cat1 option:selected").text();

    	$("#tax_location_cat2").hide();
	$(".spinner").fadeIn("slow");
    $.ajax({
        url: '/wp-admin/admin-ajax.php',
        type: 'POST',
        data: {
            'action' : 'sec_location_ajax',
            'parent' : selectedArea
        },
        dataType: 'html'
    })

    .success(function(results){
        $('#tax_location_cat2').html(results);
        $(".spinner").hide();
        $("#tax_location_cat2").fadeIn("slow");

    })
    .fail(function( jqXHR, textStatus ) {
        console.log( "Request failed: " + textStatus );
    });

}

//window.onload = ajaxloop;
document.getElementById("tax_location_cat1").onchange = ajaxloop;
	
});
    </script>

----- Function i used in functions.php
// Second location select search ajax
function sec_location_ajax() {
$taxonomies = array( 
    'location_cat',
);
$parent_name  = $_POST['parent']; 
    var_dump($parent_name);
$parent = get_term_by('name', $parent_name, 'location_cat');
$args = array(
    'orderby'           => 'name', 
    'parent' 			=> $parent->term_id,
); 

$ajaxQuery = get_terms($taxonomies, $args);

    ob_start();

       ?>
        <select>
       <?php
       foreach ($ajaxQuery as $sec_location){
    ?>

       <option><?php echo($sec_location->name); ?></option>
        <?php /** Normal Loop Stuff **/ ?>

    <?php
	    }
	    ?>
	    </select>
	    <?php

    $htmlContent = ob_get_clean();
    echo $htmlContent;
    exit;
}
add_action('wp_ajax_nopriv_sec_location_ajax', 'sec_location_ajax');
add_action('wp_ajax_sec_location_ajax', 'sec_location_ajax');
