### ISSUE TITLE
term_args not working on taxonomy

### ISSUE THREAD

**Issue by yefrat** [bootsz/wp-advanced-search#166]
Hi, 
im using the latest wp 4.3
and wp advanced search 1.4.2
Im trying to use 'term_args' on my taxonomy field with no success.
im using this piece of code:

    $args['fields'][] = array('type' => 'taxonomy',
                          'taxonomy' => 'location_cat',
                          'format' => 'select',
                       //   'nested' => true,
                          'term_args' => array(
                          		       'hide_empty' => false, 
                                               'orderby' => 'title', 
                                               'order' => 'ASC'),
                          'allow_null' => 'Area',       
                                      
                          );

no metter what i change under 'term_args' nothing happen. 

any help would be  appreciated.

**Comment by bootsz** [comment]
I think I know what the issue is.  In src/Field.php, on line 60, change to:

```
'id' => 1,
'term_args' => 1
```

Let me know if that fixes it for you.

**Comment by yefrat** [comment]
works perfect thank you
