### ISSUE TITLE
Show a breadcrumb of searched terms

### ISSUE THREAD

**Issue by fmaso** [bootsz/wp-advanced-search#168]
Hello,
Is it possible to show to the user the search parameter he used like a breadcrumb?

For example: 
"you search term are: name of category, name of custom field, name of taxonomy etc...

**Comment by bootsz** [comment]
There isn't anything built in that does that but you could make it yourself. If you're using standard search mode you could grab the query information using PHP's ```$_GET``` to determine what field values were entered.  Or using jQuery, examine the form field values.
