### ISSUE TITLE
User Query

### ISSUE THREAD

**Issue by jillmolloy** [bootsz/wp-advanced-search#169]
I was wondering if it's possible to use this search with WP_User_Query instead of WP_Query? I have a lot of users for my site and I'm trying to create a searchable directory of them.

Many thanks for your work on this awesome tool!

**Comment by bootsz** [comment]
Not possible, unfortunately.  The entire framework is built around WP_Query which is completely different from WP_User_Query.  Might be possible as part of a major overhaul in the future but it's not a priority for me right now.  Sorry
