### ISSUE TITLE
Search Results not Returning

### ISSUE THREAD

**Issue by fridaynext** [bootsz/wp-advanced-search#176]
I'm trying to set up a WPAS form that has a text field for search (CPT titles) and a separate text field for artist search (CPT ACF Field "artist").  The artist field works fine, but when I attempt to search in the regular search field, nothing is returned.

Here's the form setup:
https://gist.github.com/fridaynext/f7b6a60b6db083688153

And here's the debug output:
https://gist.github.com/fridaynext/55f6d2cc2da0f1f95408

Is there something obvious I'm doing incorrectly in my code here?

**Comment by fridaynext** [comment]
Just to clarify, I've been working on this for about 5 hours, and have read the documentation and tried multiple combination of form setups to get it to work, but I still can't manage to get the "search" box to actually search custom post types.  I've also read the help page, and I believe I've provided enough info here, but please correct me if I need to post more!

**Comment by Mte90** [comment]
same problem

**Comment by Mte90** [comment]
I've tried with the release 1.4.1 and that version don't have this problem.

**Comment by Mte90** [comment]
Ok I've tried with a blank profile and I can see that the post_type in debug information is different from the config.

**Comment by fridaynext** [comment]
Do you mean in my config?  I've just tried 1.4.2 and 1.4.1, and I'm still getting no results when I type in the search field.  "Artist" (ACF) field still works fine.

**Comment by fridaynext** [comment]
I'm looking, and it appears I'm using the 'music' post type, spelled correctly, and debug info looks to mirror that.

**Comment by Mte90** [comment]
In my case is different :-/

**Comment by fridaynext** [comment]
I'll update to 1.4.2 and remove all the extra fields to see if just the search field can search the 'music' CPT.

**Comment by Mte90** [comment]
After some testing after the pressing of the button the posttype is changed

**Comment by fridaynext** [comment]
I'm using an AJAX form, so I don't have a submit button to press, but my debug is showing the post type still the same...

**Comment by Mte90** [comment]
check in the sql code in the debugger, i also use the ajax form but I've added the button

**Comment by fridaynext** [comment]
I just checked my sql code, and it's showing the same post type.  But the search function still isn't working.  I wonder what version the demo form on the website is using, since that one seems to work.

**Comment by Mte90** [comment]
In my case in src/Factory.php there are some problems in wp_query

**Comment by fridaynext** [comment]
The strange thing is, with nothing in the search box, it will list every single 'music' post type listed in the order I choose; however, once I enter a search query, it returns nothing.

**Comment by Mte90** [comment]
```
WPAS DEBUG
------------------------------------
|| Errors
------------------------------------
No errors detected.
------------------------------------
|| WP_Query Arguments
------------------------------------
Array
(
    [post_type] => Array
        (
            [0] => immobile
        )

    [orderby] => title
    [posts_per_page] => 10
    [post_status] => Array
        (
            [0] => published
        )

    [s] => ap
    [tax_query] => Array
        (
            [0] => Array
                (
                    [taxonomy] => provincia
                    [operator] => AND
                    [field] => slug
                    [terms] => rieti
                )

        )

    [paged] => 1
)

------------------------------------
|| MySQL Query 
------------------------------------
SELECT SQL_CALC_FOUND_ROWS  wp_posts.ID FROM wp_posts  WHERE 1=1  AND ( 
  (
				SELECT COUNT(1)
				FROM wp_term_relationships
				WHERE term_taxonomy_id IN (3)
				AND object_id = wp_posts.ID
			) = 1
) AND (((wp_posts.post_title LIKE '%ap%') OR (wp_posts.post_content LIKE '%ap%')))  AND (wp_posts.post_password = '')  AND wp_posts.post_type = 'urbani' GROUP BY wp_posts.ID ORDER BY wp_posts.post_title DESC LIMIT 0, 10
------------------------------------
|| Request Data 
------------------------------------
Array
(
    [search_query] => ap
    [tax_provincia] => rieti
    [paged] => 1
    [wpas_id] => modulo_orizzontale
    [wpas_submit] => 1
)
```
As you can see in the wp_query and in the sql after the ajax search the value is different

**Comment by fridaynext** [comment]
That is strange... I've removed everything except the search form, and it still doesn't work when I type in any string into the search form.  Blank search form returns all CPT's I'm searching for.

**Comment by fridaynext** [comment]
Here's the form on the web.  I'll enable debugging there so you can see the debug output.

https://fs.friday-next.com/music-database-search/

**Comment by fridaynext** [comment]
Actually, #173 worked to fix this for me.  I'm not sure why it's not working for your install, but it fixed my issue, and I can now search for CPT's and ACF fields with a CPT title search variable as well.

GAH that was maddening figuring that out!
