### ISSUE TITLE
ACF + Relevanssi Search

### ISSUE THREAD

**Issue by a42** [bootsz/wp-advanced-search#201]
Hi there

First of all: Thanks for this nice and easy-going framework for making the search on WordPress better.

I have in the Issues that the previously have been trouble with ACF and Relevanssi Search, is this still applicable for the version at hand ?

I my setup is like this  >> https://gist.github.com/a42/087ddcd4052ca532db95

When applying the form to a search page I get the following debug >> https://gist.github.com/a42/0d13954d50a2e5235ba1

In the first select I get all post, in the second and third select only shows one (the first) value of the acf field...

Am I missing something ? 

Cheers,
Adam

**Comment by bootsz** [comment]
Does the search work properly without Relevanssi enabled?  If so have you tried the fix offered in #173?

**Comment by a42** [comment]
The search works with only the post selects. And there are no difference between Relevanssi enabled/disabled. Yes I have tried the fix.

**Comment by bootsz** [comment]
Ok.  I also don't understand what you're trying to do with the functions farver_value and by_value.  I assume you're trying to automatically enumerate all of the possible values for each field and populate a select field with them.  But these functions are not returning a key->value array.  You are just resetting $value every time and then returning whatever $value equals for the very last value.

**Comment by a42** [comment]
oh... how should I then format that function ?

**Comment by bootsz** [comment]
I'm not sure, but maybe just this:
```
if ($field) return $field['choices']
```

**Comment by a42** [comment]
I have tried that - returns 'Array' in the select list... :)

**Comment by bootsz** [comment]
Use "values" instead of "value" in each field configuration

**Comment by a42** [comment]
that did it! Thanks a million ++ Cheers!

The Very Best
Adam

**Comment by a42** [comment]
Ok, I'm back... The above solution worked when accessing acf select fields to be used in a wpas select field...

but when accessing a acf text field to be used in a wpas select field I get nothing ...

the function from where I pull the values is:

function make_value() {
	$field_key = 'field_5695860ff06c7';
	$field = get_field_object($field_key) ;
	
	if ($field) return $field['choices'];	 
}

and for the args : 

$args['fields'][] = array(
			'type' => 'meta_key',
			'meta_key' => 'make',
			'format' => 'select',
			'values' => make_value(),
			'allow_null' => 'Mærke',
			'compare' => 'LIKE',
			'data_type' => 'ARRAY<CHAR>');

Where I'm doing wrong ?

**Comment by a42** [comment]
the late line 'data_type' is:

'data_type' => 'ARRAY<CHAR>'

...

**Comment by bootsz** [comment]
Not sure but I think if the field in ACF is a text field then there is no attribute 'choices', since unlike a select field, a text field can take on any value.  So it's not possible to pre-populate a select field automatically in that case.

**Comment by a42** [comment]
the acf field is a text field ... How can I then fecth all values with a certain key ? 

And how or what should I pass it on to the private function select($multi = false) { } as seen in src/InputMarkup.php

**Comment by bootsz** [comment]
I don't know if ACF has any built-in method that will do that for you.  You'll have to look at the ACF docs.  It could also be done using a custom query to get all posts and accumulate all the unique values for the particular meta_key.  Could be slow if you have thousands of posts, though.

**Comment by a42** [comment]
it's only a search through max 200 post... I'll look a the custom query ...

**Comment by a42** [comment]
I have now updated the function to this

    function dropdown_values() {

    $args = array( 'post_type' => 'post' , 'post_status' => 'publish' , 'post_per_p$
   $getposts = get_posts( $args );

       foreach($getposts as $post) : setup_postdata($post);
       $themeta = get_post_meta($post->ID,'dyr',true);
       $meta_data[] = array(
                                         $themeta => $themeta,);
       return json_encode( $meta_value ); 

       endforeach;
    }

and the form to

      $args['fields'][] = array('type' => 'generic',
                                      'id' => 'dyr',
                                      'format' => 'select',
                                      'values' => dropdown_values(),
                                      "allow_null" => "vælg et dyr",
                                      'compare' => '=');

But nothing are displayed in the dropdown select on the page - how should I format the return from the function dropdown_values() ; ?
