### ISSUE TITLE
Slider as a format?

### ISSUE THREAD

**Issue by a42** [bootsz/wp-advanced-search#202]
Hi there 

I wonder if it could be a future feature to include the ability to make a slider as format for the sake of filtering of numbers ?

Cheers,
Adam

**Comment by bootsz** [comment]
Maybe.  You can add your own using a jQuery plugin.  I think someone else has done that, it's somewhere in the closed issues.

**Comment by a42** [comment]
Cheers! I will have a look :)

/Adam
