### ISSUE TITLE
PHP Warning:  array_reverse() expects parameter 1 to be array, string given in 

### ISSUE THREAD

**Issue by a42** [bootsz/wp-advanced-search#203]
hi there

This issue has to do with #201 : 

In stead of fetching acf text field values with acf's get_field / get_field_object functions I do like this

    function key_value_select( $key ) {

     $args = array( 'post_type' => 'post' , 'post_status' => 'publish' , 'post_per_page' => -1);
     $getposts = get_posts( $args );

        foreach($getposts as $post) : setup_postdata($post);
            $themeta = get_post_meta($post->ID, $key ,true);
            
            $meta_value  = $themeta;
            $meta_value .= ' => ';
            $meta_value .= $themeta;
            $meta_value .= ' , ';
            
        endforeach;
        
        return $meta_value;

     }

and using the function in the form creation like this

    $args['fields'][] = array('type' => 'generic',
         		              'id' => 'dyr',
		                      'format' => 'select',
                 		      'values' => key_value_select('dyr'),
		                      "allow_null" => "vælg et dyr",
		                      'compare' => 'LIKE',
		                      'data_type' => '<CHAR>');

When executing the page I get following PHP Warning in the debug.log

PHP Warning:  array_reverse() expects parameter 1 to be array, string given in /wp-advanced-search/src/Input.php on line 135

If I comment line 135 out the other three selectors are empty with only the allow_null value displayed.

Any sugestions to how I get passed this bumb on the road to bliss ?

Cheers
Adam

**Comment by a42** [comment]
I have now - almost - solved the issue... the function is like this now:

     function key_value_select( $key ) {
     global $wpdb;
   
     $args = array( 'post_type' => 'post' , 
                  'post_status' => 'publish' , 
                  'post_per_page' => -1);
                  
     $posts = get_posts( $args );
   
     $animals = array();
        foreach($posts as $p){
        $animal = get_post_meta($p->ID,"dyr",true);
        if( ! in_array( $animal, $animals) )
        
            $animals[] = $animal;
            
        }

      return $animals;

      }

This populates the select as follows:

    <select id="dyr" name="dyr" class="wpas-select ">
            <option value="">vælg et dyr</option>
            <option value="0">pingvin</option>
            <option value="1">bjørn</option>
            <option value="2">frø</option>
     </select>

as you see the option value is 0 -> 2 and we want it to be value="pingvin", value="bjørn" or value="frø" - how can I pass this value to the creation of the select values ?

Cheers,
Adam

**Comment by a42** [comment]
... and when applying this setup to another wordpress setup it only display at the most 5 options in each select...

Is there an parameter in which I can get the select options populated with all meta_values from each meta_key and not showing duplicates?

:)
Adam

**Comment by a42** [comment]
ok, I have tracked down to src/Factory.php:153-154 where the input to the generic fields are initialized 

     if ($field_type == FieldType::generic)
                        $name = empty($input_args['id']) ? 'generic' : $input_args['id'];

But how do I get the value of the option to be the same as the value shown in the dropdown as this

    <option value="pingvin">pingvin</option>

and the single option for a select field in src/InputMarkup.php line 309-323

    private function selectOption($value, $label, $level = 0) {
        $indent = '';
        if ($level > 0) {
            for($i=0; $i<$level; $i++) {
                $indent .= "—";
            }
            $indent .= ' ';
        }
        $output = '<option value="'.$value.'"';
        if (in_array($value, $this->input->getSelected())) {
            $output .= ' selected="selected"';
        }
        $output .= '>'.$indent.$label.'</option>';
        return $output;
    }

But the option value are set to numbers instead of text  when the type is 'generic'?

**Comment by bootsz** [comment]
It's because your key_value_select function is incorrect.  You're building an array with just values and no keys, so in PHP the keys default to 0,1,2,etc.  Perhaps you might want to read up on how arrays work in PHP.

**Comment by a42** [comment]
:) yep! have done that and when creating the array

     $values = array($value => $value);
     return $values;

inside loop only returns one line...

**Comment by a42** [comment]
ok... solution were just in front of me...

     $values[$value] = $value;

return the value to be used in the generic types I am using... 

Next problem *sigh* is that when choising one parameter from a dropdown it does not respond as expected. The args for a generic select (and checkbox) field:

     $args['fields'][] = array(
			'type' => 'generic',
			'id' => 'make',
			'format' => 'select',
			'values' => key_value_select('make'),
			'allow_null' => 'Mærke',
			'compare' => 'LIKE',
			'data_type' => 'ARRAY<CHAR>');

How to get I to work ?

Cheers,
Adam
