### ISSUE TITLE
how to use a variable in tax_query?

### ISSUE THREAD

**Issue by maurice1976** [bootsz/wp-advanced-search#215]
Hello,

I'm trying to setup a search that uses a variable $parentz as term. Sadly I'm not able to achieve this. I used several methods (terms as array, terms as single value) but none seem to work.

The variable is a global variable declared in a different function.
I'm able to echo the value so it is available in the function.
Passing the variable directly into the terms does not work.
When I declare a new variable and use a value ($parentz = '28'; instead of variable $parentz = $parent_section_var;) the search is executed in the expected way.

So why is the following not working? Any pointers would be greatly appreciated!

function knowledgebase_simplesearchkb() {
       
        global $parent_section_var;
        //echo $parent_section_var; // getoond op scherm dus variablee is beschikbaar
        
        $parentz = (string)$parent_section_var;
        //$parentz = $parent_section_var; // als gevuld met 28 wordt dit goed verwerkt als argument
        print $parentz;
        
        $args = array();
        
        $args['wp_query'] = array( 'post_type' => array('field', 'param', 'article', 'knowledge_base'), 
                               'orderby' => 'title', 
                               'order' => 'ASC',
                               'post_status' => 'publish',
        //excluding 404 page, activity page, groups page from search
                               'post__not_in' => array(534, 1962, 2021),   
                               'tax_query' => array(
                                                    array(
                                                        'taxonomy' => 'section',            //(string) - Taxonomy.
                                                        'field' => 'id',                    //(string) - Select taxonomy term by ('id' or 'slug')
                                                        'terms' => $parentz,               //(int/string/array) - Taxonomy term(s).
                                                        'include_children' => true,         //(bool) - Whether or not to include children for hierarchical taxonomies. Defaults to true.
                                                        'operator' => 'IN'                  //(string) - Operator to test. Possible values are 'IN', 'NOT IN', 'AND'.
                                                         ),)
                            );

**Comment by Psicografici** [comment]
I have the same problem.

**Comment by maurice1976** [comment]
Hi Psicografici, we solved it by using $_SESSION instead of $GLOBALS to pass the variable.
