### ISSUE TITLE
How to do a filter between 2 input text.

### ISSUE THREAD

**Issue by LeFrenchie** [bootsz/wp-advanced-search#28]
Is it possible to do that with meta_key field ?

![capture decran 2013-11-13 a 15 57 17](https://f.cloud.github.com/assets/3471181/1532244/f2c466b0-4c73-11e3-948c-b317956845fd.png)

Thx !

**Comment by bootsz** [comment]
Hey all, for anyone still looking to implement this:

This is supported in an upcoming version which is now available as a beta release. In this version you can do BETWEEN comparisons using either multiple inputs or a single input.

Code: https://github.com/bootsz/wp-advanced-search/archive/1.4-beta.zip

Documentation: 
http://wpadvancedsearch.com/beta/param/inputs/
http://wpadvancedsearch.com/beta/param/compare/

If you happen to give it a try please report back with your results.

**Comment by chadopenorigin** [comment]
Hi, Apologies for reopening this issue, but I've been struggling to recreated the min & max "select type input" as depicted above.

I've followed your implementation suggestions above, but no luck.
Hoping someone could steer me in the right direction?

Code:
`
	$args['fields'][] = array(
	    'type' => 'meta_key',
	    'label' => 'Price Range',
	    'meta_key' => 'prop_price',
	    'compare' => 'BETWEEN',
	    'data_type' => 'NUMERIC',
	    'inputs' => array(
	        array(
	            'format' => 'select',
	            'value' => array(
	            				':50' => '50 & under',
	            				':100' => '100',
	            				':200' => '200',
	            				':300' => '300'
	            				)
	            ),
	        array(
	            'format' => 'select',
	            'value' => array(
	            				'50:' => '50 & over',
	            				'100:' => '100',
	            				'200:' => '200',
	            				'300:' => '300')
	            ),
	        )
	    );
`
Results:
![screen shot 2016-11-20 at 8 08 16 pm](https://cloud.githubusercontent.com/assets/23617918/20465120/ea61090a-af5e-11e6-90c0-661f813854bd.png)

Thanks!
