### ISSUE TITLE
How do I compare the user input to my meta_key if my meta_key is not a single value but an array of values ?

### ISSUE THREAD

**Issue by zeeaq** [bootsz/wp-advanced-search#47]
I am building a website to display products using your amazing plugin and the 'advance custom fields' plugin.

I have problems displaying results when the meta_key in question stores more than one value which has to be compared to the user input.

Say for instance, I'm creating a product page about a particular model of smartphone called 'Phone XYZ'. I have a custom field where I can select the available colours in the form of checkboxes. Since 'Phone XYZ' is available in 'blue', 'red' and 'green' colours, I check these on the product edit page.

Now if a user searches for any phone that's available in say 'red' colour, I want Phone XYZ to show up in the results. But I'm not able to make it work like that.

Is this code correct for what I'm trying to achieve?

$args['fields'][] = array('type' => 'meta_key',
				'meta_key' => 'colour',
			        'label' => 'Colour',
				'format' => 'select',
				'data_type' => 'CHAR',
				'compare' => 'IN',
				'values' => array( '' => 'Select Colour', 'red' => 'Red', 'blue' => 'Blue', 'green' => 'Green', 'yellow' => 'Yellow', 'white' => 'Whitw', 'black' => 'Black'));

**Comment by bootsz** [comment]
Hey all,

I know it has been a while but I'm preparing a new version which address this issue.  A beta release is available for testing if you care to try it out.  You can get the code here: https://github.com/growthspark/wp-advanced-search/tree/1.4-beta

The solution is to set 
```
'data_type' => 'ARRAY<CHAR>'
```
On your meta_key field.

This is a beta release and may not be stable so please use with caution. Requires PHP >= 5.3 and WordPress >= 4.1.
