### ISSUE TITLE
Searches by keywords field but not by taxonomy select menus

### ISSUE THREAD

**Issue by parfy1978** [bootsz/wp-advanced-search#50]
Hi,

I've incorporated the search within the Twenty13 theme as a test. I have one keyword search textfield and three select menus which target Taxonomies related to a 'Vacancy' Post Type. See screenshot below.

When I use the keyword textfield, the search results come back with 2 matching results (screenshot 2), which seems to be working fine - but when I use any of the Taxonomy select menus, ALL of the posts associated with 'Vacancy' show up - and I know one of them definitely does NOT match the search criteria but still shows up in the results (screenshot 3).

![advanced-search-example](https://f.cloud.github.com/assets/1633650/2373162/67b09b94-a848-11e3-9f47-479c064900ee.jpg)

Code I'm using:

$args = array();

        $args['form'] = array('action' => 'http://www.mydomain.com/wp-advanced-search-results/');

		$args['wp_query'] = array('post_type' => 'vacancy',
								  'posts_per_page' => 2,
								  'orderby' => 'date',
								  'order' => 'DESC'
								  );

		$args['fields'][] = array('type' => 'search',
		                          'placeholder' => 'Enter keywords...',
		                          'value' => '');

		$args['fields'][] = array('type' => 'taxonomy',
								  'taxonomy' => 'job_category',
		                          'operator' => 'IN',
		                          'format' => 'select',
		                          'allow_null' => 'Job category');

		$args['fields'][] = array('type' => 'taxonomy',
								  'taxonomy' => 'location',
		                          'operator' => 'IN',
		                          'format' => 'select',
		                          'allow_null' => 'Location');

		$args['fields'][] = array('type' => 'taxonomy',
								  'taxonomy' => 'job_type',
		                          'operator' => 'IN',
		                          'format' => 'select',
		                          'allow_null' => 'Job type');

		$args['fields'][] = array('type' => 'submit',
								  'value' => 'Search');

Great search by the way!

Thanks for any help you can offer, I'm hoping to use this in an upcoming project.

**Comment by melens69** [comment]
parfy1978, have you found the solution? i have the same problem that you, and i get zero result.
Thanks and regards.

**Comment by parfy1978** [comment]
Hi Melens69,

Sorry for the delay, unfortunately time was against me so I ended up using an alternative plugin.

**Comment by bootsz** [comment]
For anyone still experiencing this issue, you can try enabling WPAS_DEBUG and examining the output, particularly the wp_query object that is generated from your arguments.  This may help illuminate the problem.

```
define('WPAS_DEBUG',true);
```
