### ISSUE TITLE
Possible pagination bug

### ISSUE THREAD

**Issue by jfc4** [bootsz/wp-advanced-search#51]
Thank you for your hard work on WPAS, it works well.

There may be a bug:
1 - If you setup a custom post type (events) and set the has_archive attribute to false
2 - Create a page named events and use it as a search events page
3 - Pagination hasn't been working on the events page; the search works fine, but after clicking on the "next" link or another page link, I get a 404 message

**Comment by bootsz** [comment]
This is a WordPress quirk rather than a problem with WPAS.

Here is a good solution which I've verified will work in your situation: http://wordpress.stackexchange.com/a/9705

For a post type called "events" you would add this:
```
add_rewrite_rule( 'events/page/([0-9]+)/?$', 'index.php?pagename=events&paged=$matches[1]', 'top' );
```

**Comment by jfc4** [comment]
Thanks for the update. Will give it a try.
