### ISSUE TITLE
Using WP Advanced Search to find distance

### ISSUE THREAD

**Issue by nicolefurlan** [bootsz/wp-advanced-search#78]
Hi! I'm currently building a Wordpress website which hosts restaurant listings, and the theme that I purchased uses WP Advanced Search for its search feature.

I'm trying to build a radius search functionality into WP Advanced Search - so that people could search by address (which basically would return a list of our "listing" post type, with the closest at the top). The full address and values of lat/long are currently in each restaurant listing's meta data, and I've figured out how to get the distance between address X and address Y using Google Maps in php. Do you have any idea what I would add to $args to get this done?

Thanks so much!

**Comment by bootsz** [comment]
This is supported in an upcoming version which is now available as a beta release. In this version you can do BETWEEN comparisons using either multiple inputs or a single input.

Code: https://github.com/bootsz/wp-advanced-search/archive/1.4-beta.zip

Documentation: 
http://wpadvancedsearch.com/beta/param/inputs/
http://wpadvancedsearch.com/beta/param/compare/

If you happen to give it a try and run into any trouble feel free to re-open this issue.
