### ISSUE TITLE
Sorting options

### ISSUE THREAD

**Issue by arafail** [bootsz/wp-advanced-search#90]
Hi guy!
First of all, awesome job, this seems to be exactly what i need, however i have a small issue:
I have this type of category tree:

category1
--subcat1-1
--subcat1-2
--subcat1-3

category2
--subcat2-1
--subcat2-2
--subcat2-3

I am trying to make 2 category select boxes appear (one for the top level, one for the child level), and while i have a good idea on how to populate them (use the terms option), i cannot seem to make 2 select boxxes appear.
Only one shows.
Can you please point me in the right direction?
Thank you!

**Comment by bootsz** [comment]
This is supported in an upcoming version which is now available as a beta release.  In this version you can configure multiple inputs for a single taxonomy.

Code: https://github.com/bootsz/wp-advanced-search/archive/1.4-beta.zip

Documentation: http://wpadvancedsearch.com/beta/param/inputs/
