### ISSUE TITLE
Can't get values from array

### ISSUE THREAD

**Issue by avatar876575** [bootsz/wp-advanced-search#95]
Hey there! Great plugin! I just have one problem - can't get the values from my meta field which is an array.

**Comment by bootsz** [comment]
Sorry I know this was a while ago but the next version (now in beta) fixes this issue.  You can get the code here: https://github.com/growthspark/wp-advanced-search/tree/1.4-beta

The solution is to set ```'data_type' => 'ARRAY<CHAR>'```

This is a beta release and may not be stable so please use with caution.  Requires PHP >= 5.3 and WordPress >= 4.1.
